# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=20, unique=True)),
                ('a_content', models.TextField()),
                ('a_keywords', models.CharField(max_length=30)),
                ('a_describe', models.CharField(max_length=100)),
                ('a_titlepic', models.ImageField(null=True, upload_to='article')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'db_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'db_articletype',
            },
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'db_superuser',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='a_f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backsys.ArticleType'),
        ),
    ]
